display-config
MirServer/mir-kiosk pull request #12
Opened 2018-09-26 16:05 UTC by AlanGriffiths

Add logic for an optional "display-config" setting.

If "snapctl get display-config" is set we compare with the `.display` file (if it exists) and unless they are the same overwrite and restart.

2018-09-26 16:11 UTC, AlanGriffiths commented
Oops. Sorry broke the logic.

2018-09-27 14:18 UTC, Saviq requested changes
Just a couple nits

2018-09-27 14:18 UTC, Saviq commented on snap/hooks/configure
> +if [ -n "${display_config}" ]; then
Hmm so if we set it to empty, the file will remain, along with the "DO NOT EDIT" header... Maybe we could check if the file was written by us (i.e. has the `# DO NOT EDIT` header) and remove it if that's the case?

2018-09-27 14:18 UTC, Saviq commented on snap/hooks/configure
> +  echo "${display_config}"                                                  >> "$SNAP_DATA/miral-kiosk.display~"
I suppose `$SNAP_DATA/miral-kiosk.display` deserves a variable of its own?

2018-09-28 14:50 UTC, Saviq approved these changes
Yeah this is fine, although screams for refactoring.

2018-09-28 14:50 UTC, merged