Safer startup logic
MirServer/mir-kiosk pull request #50
Opened 2020-12-09 16:47 UTC by AlanGriffiths

Don't use snapctl on `run-daemon`, it is racy and can fail some of the time on some systems.

See https://forum.snapcraft.io/t/scummvm-snap-failing-to-install-on-rpi-4/21394/59

2020-12-10 00:51 UTC, wmww approved these changes
Looks good to me. *if* you wanted me to test that it works I'd need more context for what it's supposed to be doing in what situations.

2020-12-10 09:06 UTC, AlanGriffiths commented
> Looks good to me. _if_ you wanted me to test that it works I'd need more context for what it's supposed to be doing in what situations.

1. On installation `daemon` should default to "true" on Ubuntu Core systems and "false" on "classic" systems;
2. The `mir-kiosk.daemon` daemon should run if and only if `daemon=true`; and,
3. (what this changes) `snapctrl stop ...` should not be called from the daemon launch script, only from hooks.

2020-12-11 15:06 UTC, Saviq requested changes

2020-12-11 15:06 UTC, Saviq commented on snap/hooks/install
> +# will start it if appropriate
```suggestion
# will start and enable it if appropriate
```

2020-12-11 15:06 UTC, Saviq commented on snap/hooks/post-refresh
> +# will start it if appropriate
```suggestion
# will start and enable it if appropriate
```

2020-12-11 15:06 UTC, Saviq commented on snap/hooks/configure
> +  fi
Do we need the if? `start --enable…` should be idempotent?

2020-12-11 15:06 UTC, Saviq commented on snap/hooks/configure
> +  fi
Same here?

2020-12-11 15:06 UTC, Saviq commented on snap/hooks/configure
> +fi
Any way to avoid this if we just started the service above?

2020-12-11 15:41 UTC, Saviq commented on snap/hooks/configure
> +  fi
```suggestion
  snapctl stop --disable $SNAP_NAME.daemon 2>&1 || true
```

2020-12-14 11:12 UTC, Saviq approved these changes
Just one question, otherwise:

> - [x] On installation daemon should default to "true" on Ubuntu Core systems and "false" on "classic" systems;
> - [x] The mir-kiosk.daemon daemon should run if and only if daemon=true; and,
> - [x] (what this changes) snapctrl stop ... should not be called from the daemon launch script, only from hooks.

2020-12-14 11:12 UTC, Saviq commented on glue/bin/run-daemon
> +nohup "$@"
We didn't need the `exec` in the first place, did we?

2020-12-14 11:20 UTC, AlanGriffiths commented on glue/bin/run-daemon
> +nohup "$@"
Fixed

2020-12-14 12:39 UTC, Saviq approved these changes
Yup.

2020-12-14 12:40 UTC, merged